"""
HTML exporter for scan results.

Generates a complete standalone HTML report with embedded CSS styling.
The report includes sections for summary, API endpoints, network requests,
security findings, storage data, and threat analysis.
"""

from dataclasses import asdict
from datetime import datetime
from pathlib import Path
from string import Template
from typing import Optional

from api_scanner import __version__
from api_scanner.exceptions import ExportError
from api_scanner.exporters.base import BaseExporter
from api_scanner.scanner.models import ScanResult


class HTMLExporter(BaseExporter):
    """Exports scan results to a standalone HTML report.

    Generates a modern, professional HTML report with embedded CSS.
    The report is completely self-contained with no external dependencies.
    Features card-based layout, color-coded risk badges, and responsive design.
    """

    def export(self, scan_result: ScanResult, output_path: str) -> str:
        """Export scan results to an HTML report file.

        Args:
            scan_result: The scan result data to export.
            output_path: The file path where the HTML should be written.

        Returns:
            The path to the created HTML file.

        Raises:
            ExportError: If the export operation fails.
        """
        try:
            file_path = Path(output_path)
            if not file_path.suffix:
                file_path = file_path.with_suffix(".html")

            html_content = self._build_report(scan_result)

            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text(html_content, encoding="utf-8")

            return str(file_path)

        except Exception as e:
            raise ExportError(f"Failed to export HTML: {e}") from e

    def _build_report(self, scan_result: ScanResult) -> str:
        """Build the complete HTML report string.

        Args:
            scan_result: The scan result to render.

        Returns:
            Complete HTML document as a string.
        """
        css = self._get_css()
        summary_section = self._build_summary(scan_result)
        endpoints_section = self._build_endpoints_table(scan_result)
        requests_section = self._build_requests_table(scan_result)
        storage_section = self._build_storage_section(scan_result)
        errors_section = self._build_errors_section(scan_result)

        export_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>API Scanner Report - {self._escape_html(scan_result.url)}</title>
    <style>
{css}
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>API Scanner Pro Report</h1>
            <p class="subtitle">Generated by API Scanner Pro v{__version__}</p>
            <p class="export-time">Report generated: {export_time}</p>
        </header>

        {summary_section}
        {endpoints_section}
        {requests_section}
        {storage_section}
        {errors_section}

        <footer class="footer">
            <p>API Scanner Pro v{__version__} | Report generated {export_time}</p>
        </footer>
    </div>
</body>
</html>"""
        return html

    def _get_css(self) -> str:
        """Get the embedded CSS styles for the report.

        Returns:
            CSS string for the HTML report.
        """
        return """
        :root {
            --primary: #2563eb;
            --primary-dark: #1d4ed8;
            --success: #16a34a;
            --warning: #d97706;
            --danger: #dc2626;
            --info: #0891b2;
            --bg: #f8fafc;
            --card-bg: #ffffff;
            --text: #1e293b;
            --text-muted: #64748b;
            --border: #e2e8f0;
            --shadow: 0 1px 3px rgba(0,0,0,0.1), 0 1px 2px rgba(0,0,0,0.06);
            --shadow-md: 0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -1px rgba(0,0,0,0.06);
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background-color: var(--bg);
            color: var(--text);
            line-height: 1.6;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem;
        }

        .header {
            text-align: center;
            margin-bottom: 2rem;
            padding: 2rem;
            background: linear-gradient(135deg, var(--primary), var(--primary-dark));
            color: white;
            border-radius: 12px;
            box-shadow: var(--shadow-md);
        }

        .header h1 {
            font-size: 2rem;
            font-weight: 700;
            margin-bottom: 0.5rem;
        }

        .subtitle {
            opacity: 0.9;
            font-size: 1rem;
        }

        .export-time {
            opacity: 0.8;
            font-size: 0.875rem;
            margin-top: 0.5rem;
        }

        .card {
            background: var(--card-bg);
            border-radius: 8px;
            box-shadow: var(--shadow);
            padding: 1.5rem;
            margin-bottom: 1.5rem;
            border: 1px solid var(--border);
        }

        .card h2 {
            font-size: 1.25rem;
            font-weight: 600;
            margin-bottom: 1rem;
            color: var(--primary);
            border-bottom: 2px solid var(--border);
            padding-bottom: 0.5rem;
        }

        .summary-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
        }

        .summary-item {
            text-align: center;
            padding: 1rem;
            background: var(--bg);
            border-radius: 8px;
            border: 1px solid var(--border);
        }

        .summary-item .label {
            font-size: 0.75rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: var(--text-muted);
            font-weight: 600;
        }

        .summary-item .value {
            font-size: 1.5rem;
            font-weight: 700;
            color: var(--primary);
            margin-top: 0.25rem;
        }

        .badge {
            display: inline-block;
            padding: 0.25rem 0.75rem;
            border-radius: 9999px;
            font-size: 0.75rem;
            font-weight: 600;
            text-transform: uppercase;
        }

        .badge-safe { background: #dcfce7; color: #166534; }
        .badge-low { background: #dbeafe; color: #1e40af; }
        .badge-medium { background: #fef3c7; color: #92400e; }
        .badge-high { background: #fed7aa; color: #9a3412; }
        .badge-critical { background: #fecaca; color: #991b1b; }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.875rem;
        }

        th, td {
            padding: 0.75rem 1rem;
            text-align: left;
            border-bottom: 1px solid var(--border);
        }

        th {
            background: var(--bg);
            font-weight: 600;
            color: var(--text-muted);
            text-transform: uppercase;
            font-size: 0.75rem;
            letter-spacing: 0.05em;
        }

        tr:hover {
            background: var(--bg);
        }

        .method-badge {
            display: inline-block;
            padding: 0.125rem 0.5rem;
            border-radius: 4px;
            font-size: 0.75rem;
            font-weight: 700;
            font-family: monospace;
        }

        .method-get { background: #dbeafe; color: #1e40af; }
        .method-post { background: #dcfce7; color: #166534; }
        .method-put { background: #fef3c7; color: #92400e; }
        .method-delete { background: #fecaca; color: #991b1b; }
        .method-patch { background: #e9d5ff; color: #6b21a8; }

        .status-2xx { color: var(--success); font-weight: 600; }
        .status-3xx { color: var(--info); font-weight: 600; }
        .status-4xx { color: var(--warning); font-weight: 600; }
        .status-5xx { color: var(--danger); font-weight: 600; }

        .url-cell {
            max-width: 400px;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
            font-family: monospace;
            font-size: 0.8rem;
        }

        .storage-section {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 1rem;
        }

        .storage-box {
            background: var(--bg);
            border-radius: 8px;
            padding: 1rem;
            border: 1px solid var(--border);
        }

        .storage-box h3 {
            font-size: 0.875rem;
            font-weight: 600;
            margin-bottom: 0.5rem;
            color: var(--text-muted);
        }

        .storage-box pre {
            font-size: 0.75rem;
            overflow-x: auto;
            white-space: pre-wrap;
            word-break: break-all;
        }

        .error-list {
            list-style: none;
            padding: 0;
        }

        .error-list li {
            padding: 0.5rem 1rem;
            margin-bottom: 0.5rem;
            background: #fef2f2;
            border-left: 3px solid var(--danger);
            border-radius: 4px;
            font-size: 0.875rem;
            color: #991b1b;
        }

        .empty-state {
            text-align: center;
            padding: 2rem;
            color: var(--text-muted);
            font-style: italic;
        }

        .footer {
            text-align: center;
            padding: 1.5rem;
            color: var(--text-muted);
            font-size: 0.875rem;
            border-top: 1px solid var(--border);
            margin-top: 2rem;
        }

        @media (max-width: 768px) {
            .container {
                padding: 1rem;
            }
            .summary-grid {
                grid-template-columns: repeat(2, 1fr);
            }
            .url-cell {
                max-width: 200px;
            }
        }
"""

    def _build_summary(self, scan_result: ScanResult) -> str:
        """Build the summary section of the report.

        Args:
            scan_result: The scan result to summarize.

        Returns:
            HTML string for the summary section.
        """
        scan_time = scan_result.timestamp.strftime("%Y-%m-%d %H:%M:%S")
        endpoint_count = len(scan_result.api_endpoints)
        request_count = len(scan_result.requests)
        error_count = len(scan_result.errors)
        duration = f"{scan_result.scan_duration:.2f}s"

        return f"""
        <div class="card">
            <h2>Scan Summary</h2>
            <div class="summary-grid">
                <div class="summary-item">
                    <div class="label">Target URL</div>
                    <div class="value" style="font-size: 0.9rem; word-break: break-all;">{self._escape_html(scan_result.url)}</div>
                </div>
                <div class="summary-item">
                    <div class="label">Scan Time</div>
                    <div class="value" style="font-size: 1rem;">{scan_time}</div>
                </div>
                <div class="summary-item">
                    <div class="label">Duration</div>
                    <div class="value">{duration}</div>
                </div>
                <div class="summary-item">
                    <div class="label">API Endpoints</div>
                    <div class="value">{endpoint_count}</div>
                </div>
                <div class="summary-item">
                    <div class="label">Total Requests</div>
                    <div class="value">{request_count}</div>
                </div>
                <div class="summary-item">
                    <div class="label">Errors</div>
                    <div class="value" style="color: {'var(--danger)' if error_count > 0 else 'var(--success)'};">{error_count}</div>
                </div>
            </div>
        </div>"""

    def _build_endpoints_table(self, scan_result: ScanResult) -> str:
        """Build the API endpoints table section.

        Args:
            scan_result: The scan result containing endpoints.

        Returns:
            HTML string for the endpoints table.
        """
        if not scan_result.api_endpoints:
            return """
        <div class="card">
            <h2>API Endpoints</h2>
            <div class="empty-state">No API endpoints detected during scan.</div>
        </div>"""

        rows = ""
        for endpoint in scan_result.api_endpoints:
            method_class = f"method-{endpoint.method.lower()}"
            rows += f"""
                <tr>
                    <td class="url-cell">{self._escape_html(endpoint.url)}</td>
                    <td><span class="method-badge {method_class}">{endpoint.method}</span></td>
                    <td>{endpoint.timestamp.strftime("%H:%M:%S")}</td>
                </tr>"""

        return f"""
        <div class="card">
            <h2>API Endpoints ({len(scan_result.api_endpoints)} found)</h2>
            <table>
                <thead>
                    <tr>
                        <th>URL</th>
                        <th>Method</th>
                        <th>Time</th>
                    </tr>
                </thead>
                <tbody>{rows}
                </tbody>
            </table>
        </div>"""

    def _build_requests_table(self, scan_result: ScanResult) -> str:
        """Build the network requests table section (first 50).

        Args:
            scan_result: The scan result containing requests.

        Returns:
            HTML string for the requests table.
        """
        if not scan_result.requests:
            return """
        <div class="card">
            <h2>Network Requests</h2>
            <div class="empty-state">No network requests captured during scan.</div>
        </div>"""

        display_requests = scan_result.requests[:50]
        total_count = len(scan_result.requests)

        rows = ""
        for i, req in enumerate(display_requests):
            method_class = f"method-{req.method.lower()}"
            # Find matching response for status code
            status = ""
            content_type = ""
            for resp in scan_result.responses:
                if resp.url == req.url:
                    status_class = self._get_status_class(resp.status_code)
                    status = f'<span class="{status_class}">{resp.status_code}</span>'
                    content_type = resp.content_type
                    break

            rows += f"""
                <tr>
                    <td class="url-cell">{self._escape_html(req.url)}</td>
                    <td><span class="method-badge {method_class}">{req.method}</span></td>
                    <td>{status}</td>
                    <td>{self._escape_html(content_type)}</td>
                </tr>"""

        truncated_note = ""
        if total_count > 50:
            truncated_note = f'<p style="color: var(--text-muted); font-size: 0.875rem; margin-top: 1rem;">Showing 50 of {total_count} requests</p>'

        return f"""
        <div class="card">
            <h2>Network Requests ({total_count} total)</h2>
            <table>
                <thead>
                    <tr>
                        <th>URL</th>
                        <th>Method</th>
                        <th>Status</th>
                        <th>Content-Type</th>
                    </tr>
                </thead>
                <tbody>{rows}
                </tbody>
            </table>
            {truncated_note}
        </div>"""

    def _build_storage_section(self, scan_result: ScanResult) -> str:
        """Build the storage data section.

        Args:
            scan_result: The scan result containing storage data.

        Returns:
            HTML string for the storage section.
        """
        if not scan_result.storage_data:
            return """
        <div class="card">
            <h2>Storage Data</h2>
            <div class="empty-state">No storage data captured during scan.</div>
        </div>"""

        storage = scan_result.storage_data

        # Cookies table
        cookies_html = ""
        if storage.cookies:
            cookie_rows = ""
            for cookie in storage.cookies:
                secure_badge = '<span class="badge badge-safe">Yes</span>' if cookie.secure else '<span class="badge badge-high">No</span>'
                cookie_rows += f"""
                    <tr>
                        <td>{self._escape_html(cookie.name)}</td>
                        <td>{self._escape_html(cookie.domain)}</td>
                        <td class="url-cell">{self._escape_html(cookie.value[:50])}</td>
                        <td>{secure_badge}</td>
                    </tr>"""

            cookies_html = f"""
            <div class="storage-box" style="grid-column: 1 / -1;">
                <h3>Cookies ({len(storage.cookies)})</h3>
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Domain</th>
                            <th>Value</th>
                            <th>Secure</th>
                        </tr>
                    </thead>
                    <tbody>{cookie_rows}
                    </tbody>
                </table>
            </div>"""

        # Local storage
        local_storage_html = ""
        if storage.local_storage:
            items = ""
            for key, value in storage.local_storage.items():
                items += f"  {self._escape_html(key)}: {self._escape_html(str(value)[:100])}\n"
            local_storage_html = f"""
            <div class="storage-box">
                <h3>Local Storage ({len(storage.local_storage)} items)</h3>
                <pre>{items}</pre>
            </div>"""

        # Session storage
        session_storage_html = ""
        if storage.session_storage:
            items = ""
            for key, value in storage.session_storage.items():
                items += f"  {self._escape_html(key)}: {self._escape_html(str(value)[:100])}\n"
            session_storage_html = f"""
            <div class="storage-box">
                <h3>Session Storage ({len(storage.session_storage)} items)</h3>
                <pre>{items}</pre>
            </div>"""

        return f"""
        <div class="card">
            <h2>Storage Data</h2>
            <div class="storage-section">
                {local_storage_html}
                {session_storage_html}
                {cookies_html}
            </div>
        </div>"""

    def _build_errors_section(self, scan_result: ScanResult) -> str:
        """Build the errors section.

        Args:
            scan_result: The scan result containing errors.

        Returns:
            HTML string for the errors section.
        """
        if not scan_result.errors:
            return ""

        error_items = ""
        for error in scan_result.errors:
            error_items += f"<li>{self._escape_html(error)}</li>\n"

        return f"""
        <div class="card">
            <h2>Errors ({len(scan_result.errors)})</h2>
            <ul class="error-list">
                {error_items}
            </ul>
        </div>"""

    @staticmethod
    def _escape_html(text: str) -> str:
        """Escape HTML special characters.

        Args:
            text: Text to escape.

        Returns:
            HTML-safe string.
        """
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&#x27;")
        )

    @staticmethod
    def _get_status_class(status_code: int) -> str:
        """Get CSS class for HTTP status code.

        Args:
            status_code: HTTP status code.

        Returns:
            CSS class name for the status code range.
        """
        if 200 <= status_code < 300:
            return "status-2xx"
        elif 300 <= status_code < 400:
            return "status-3xx"
        elif 400 <= status_code < 500:
            return "status-4xx"
        elif 500 <= status_code < 600:
            return "status-5xx"
        return ""
